# Generated by Django 2.2.8 on 2020-01-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='account_manager',
            field=models.UUIDField(default=123),
            preserve_default=False,
        ),
    ]
